server:
#  port: 443      #tomcat端口号,https默认端口
  port: 8080    #  tomcat端口号

#  ssl:   #搞https的.xswwj.cn域名的
#    key-store: classpath:xswwj.cn.jks
#    key-store-type: JKS
#    key-store-password: aC6LGKBtSrVrU5@

#  ssl:   #搞https的upbaby.qzhuanyou.com域名的
#    key-store: classpath:upbaby.qzhuanyou.com.jks
#    key-store-type: JKS
#    key-store-password: 92w57hrrknv
spring:
  application:
    name: doll
    #应用名称，可选
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.116.210.128:3306/doll?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      #47.120.44.182为mysql所在服务器的ip
      username: root
      #mysql用户
      password: aC6LGKBtSrVrU5@
      #mysql密码
  redis:
    host: 47.116.210.128
    port: 6379
    password: aC6LGKBtSrVrU5@   #redis的密码
    database: 0
  cache:
    redis:
      time-to-live: 3600000
#    jedis:           #Redis连接池配置
#      pool:
#        max-active: 8   #最大连接数量
#        max-wait: 1ms #连接池最大阻塞等待时间
#        max-idle: 4 #连接池中最大空闲连接
#        min-idle: 0 #连接池中最大空闲连接
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #如表address_book->AddressBook,列名user_name->userName
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
doll:
  path: D:\img1\    #window
#  path: /usr/local/img/    #linux

#用于摄像头的
camera:
  APP_KEY: 37ee314914d949f7a1be8659633b8494
  APP_SECRET: c662cfa22c1edc6cef5c4766a42ebe7e
  ACCESS_TOKEN_URL: https://open.ys7.com/api/lapp/token/get
  VIDEO_URL: https://open.ys7.com/api/lapp/v2/live/address/get

#用于控制器
mymqtt:
  brokerUrl: tcp://iot-06z00htcl0whfr4.mqtt.iothub.aliyuncs.com:1883
  deviceName: k1jfnIpmTlT
#  topic: /sys/k1fjo6CPtMr/app_dev_3/thing/event/property/post


jwt:
  secret: 12345
#  expiration: 1000*60*60*24
  expiration: 86400000


#wxPay:
##  公众号
#  appId: wxd937a072abdf46f2
#  appSecret: 555f1bc8865894eeb45e5c23966c668e
##  jsApi支付相关
#  jsApi:
##    商户号
#    mchId: 1680608250
##  商户API证书的证书序列号
#    mchSerialNo: 36EB192FE0C3489797917B03A6807B8E6DCB2DA7
#
#    apiV3Key: aswvndrbonrbnoarnbren23nfoso492s
#
#    notifyUrl:






